# Generated by Django 3.1.7 on 2021-10-30 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0104_auto_20211023_1813'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='waiver',
            table='waiver',
        ),
    ]
