# Generated by Django 3.1.7 on 2021-10-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0106_auto_20211030_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiver',
            name='time_submitted',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
